[19/Nov/2021 23:45:40] WARNING [django.request:230] Bad Request: /
[19/Nov/2021 23:47:48] WARNING [django.request:230] Not Found: /
[19/Nov/2021 23:48:18] WARNING [django.request:230] Bad Request: /
[20/Nov/2021 09:59:07] WARNING [django.request:230] Bad Request: /
[20/Nov/2021 09:59:08] WARNING [django.request:230] Bad Request: /favicon.ico
[20/Nov/2021 10:00:06] WARNING [django.request:230] Not Found: /
[20/Nov/2021 10:00:06] WARNING [django.request:230] Not Found: /favicon.ico
[20/Nov/2021 10:01:39] ERROR [django.request:230] Internal Server Error: /admin/web/message/
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: web_message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\contrib\admin\options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\contrib\admin\sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\contrib\admin\options.py", line 1697, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\contrib\admin\options.py", line 749, in get_changelist_instance
    sortable_by,
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\contrib\admin\views\main.py", line 100, in __init__
    self.get_results(request)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\contrib\admin\views\main.py", line 235, in get_results
    result_count = paginator.count
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\core\paginator.py", line 97, in count
    return c()
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\models\query.py", line 412, in count
    return self.query.get_count(using=self.db)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\models\sql\query.py", line 519, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\models\sql\query.py", line 504, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: web_message
[20/Nov/2021 10:01:43] ERROR [django.request:230] Internal Server Error: /admin/auth/user/
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: web_profile

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\contrib\admin\options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\contrib\admin\sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\contrib\admin\options.py", line 1815, in changelist_view
    'selection_note': _('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: web_profile
[20/Nov/2021 10:06:21] WARNING [django.request:230] Bad Request: /
[20/Nov/2021 10:06:48] ERROR [django.request:230] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\defaulttags.py", line 1034, in find_library
    return parser.libraries[name]
KeyError: 'staticfiles'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\PycharmProjects\Industry_Academy\web\views.py", line 16, in index
    return render(request, 'homepage.html', locals())
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\defaulttags.py", line 1091, in load
    lib = find_library(parser, name)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\defaulttags.py", line 1038, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'staticfiles' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
[20/Nov/2021 10:13:18] ERROR [django.request:230] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\defaulttags.py", line 1034, in find_library
    return parser.libraries[name]
KeyError: 'staticfiles'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\PycharmProjects\Industry_Academy\web\views.py", line 16, in index
    return render(request, 'homepage.html', locals())
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\defaulttags.py", line 1091, in load
    lib = find_library(parser, name)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\defaulttags.py", line 1038, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'staticfiles' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
[20/Nov/2021 10:18:53] ERROR [django.request:230] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\defaulttags.py", line 1034, in find_library
    return parser.libraries[name]
KeyError: 'staticfiles'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\PycharmProjects\Industry_Academy\web\views.py", line 16, in index
    return render(request, 'homepage.html', locals())
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\defaulttags.py", line 1091, in load
    lib = find_library(parser, name)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\template\defaulttags.py", line 1038, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'staticfiles' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
[20/Nov/2021 10:19:58] WARNING [django.request:230] Not Found: /post
[20/Nov/2021 10:20:00] WARNING [django.request:230] Not Found: /system
[20/Nov/2021 10:20:03] WARNING [django.request:230] Not Found: /report
[20/Nov/2021 10:20:06] WARNING [django.request:230] Not Found: /listCompany
[20/Nov/2021 10:27:05] WARNING [django.request:230] Not Found: /system
[20/Nov/2021 10:27:11] WARNING [django.request:230] Not Found: /listCompany
[20/Nov/2021 11:21:40] WARNING [django.request:230] Not Found: /favicon.ico
[20/Nov/2021 11:21:53] WARNING [django.request:230] Not Found: /listCompany
[20/Nov/2021 11:22:35] WARNING [django.request:230] Not Found: /system
[20/Nov/2021 11:26:28] WARNING [django.request:230] Not Found: /listCompany
[20/Nov/2021 18:24:41] WARNING [django.request:230] Not Found: /favicon.ico
[20/Nov/2021 18:24:42] WARNING [django.request:230] Not Found: /listCompany
[20/Nov/2021 18:24:47] WARNING [django.request:230] Not Found: /report
[20/Nov/2021 18:24:49] WARNING [django.request:230] Not Found: /system
[20/Nov/2021 18:24:51] WARNING [django.request:230] Not Found: /post
[20/Nov/2021 18:27:53] WARNING [django.request:230] Not Found: /system
[20/Nov/2021 18:28:08] WARNING [django.request:230] Not Found: /system/company/companyEdit
[20/Nov/2021 18:28:11] ERROR [django.request:230] Internal Server Error: /company/companyEdit/
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\user\PycharmProjects\Industry_Academy\company\views.py", line 46, in company_edit
    if request.user.profile.role == Profile.COMPANY:
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\utils\functional.py", line 247, in inner
    return func(self._wrapped, *args)
  File "C:\Users\user\PycharmProjects\Industry_Academy\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 424, in __get__
    self.related.get_accessor_name()
django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
